### ISSUE TITLE
Workout Start

### ISSUE THREAD

**Issue by mkduer** [mkduer/lift-weights#110]
- [x] display exercises with quantitative measurements (form input) #114
- [x] display start time #114
- [x] create add icons that add another set when selected #115 
- [x] default values to zero #115
- [x] fix values/placeholders when adding #116
