### ISSUE TITLE
Draft User Profile Page

### ISSUE THREAD

**Issue by mkduer** [mkduer/lift-weights#28]
- [x] nav bar #31 
- [x] tabs to secondary pages #32
- [x] add links to navbar and tabs #40
- [x] pass user-specific details after a successful login #41
- [x] populate profile page with test data from API (if possible) or provide data #30

**Comment by mkduer** [comment]
- [ ] pass username after unique session is created #64
