### ISSUE TITLE
Save Workout

### ISSUE THREAD

**Issue by mkduer** [mkduer/lift-weights#77]
- [x] when workout is saved, pass necessary data to backend
- [x] design workout/exercise/etc tables, as needed for DB
- [x] create tables
- [x] parse exercise objects passed to backend #77
- [x] add data to workout/exercise tables to save data on backend #80
- [x] confirm that the workout data can be fully retrieved #80
