### ISSUE TITLE
Workout Creation :: Dynamic Adjustments for Cleaner Demo (MVP goal)

### ISSUE THREAD

**Issue by mkduer** [mkduer/lift-weights#87]
- [x] close modal on Save #85
- [x] dynamically add a workoutCard after a new workout is created #91
- [x] dynamically adjust width of Workout tab after cards are added #90
- [x] update top half of WorkoutModal height when exercises are added (currently hard-coded and should be dynamically updated) #92
